FROM node:16-alpine

WORKDIR /usr/src/app

# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#node-gyp-alpine
RUN apk add --no-cache --virtual python
RUN apk add --no-cache --virtual .gyp make g++

COPY package*.json ./

RUN npm install

# Execute patch-package
RUN npm run postinstall

# Copy files from host to container
COPY ./ ./

RUN npm run build

RUN ls -al

EXPOSE 8080

CMD [ "npm", "start" ]
