name: CI
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

  pull_request:
    paths-ignore:
      - '**/README.md'

env:
  # https://typicode.github.io/husky/#/?id=with-env-variables
  HUSKY: '0'
  IMAGE_NAME: $(echo 'console.log("${{ github.repository }}".toLowerCase())' | node -)

jobs:
  build-source-code:
    name: 'Build Source Code'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Build project
        run: pnpm build

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -f Dockerfile -t ${{ env.IMAGE_NAME }}:build .
